### ISSUE TITLE
Unhandled Exception 

### ISSUE THREAD

**Issue by ElizabethHanson1999** [PremiumRAT/PureCrypter#1]
hi 
thank you for sharing 
I tried that and i got this error message : 
![image](https://user-images.githubusercontent.com/115332667/202886337-3b623a1a-06ed-4ccd-bd2e-368fa0261967.png)

**Comment by PremiumRAT** [comment]
This will be fixed by tomorrow sorry

**Comment by PremiumRAT** [comment]
It's now fixed
